#!/usr/bin/env bash
set -x

pid=0

term_handler() {
  rm -f /opt/consul/conf/smashing-consul.json
  rm -f /etc/goss/smashing-goss.yaml  
  
  if [ $pid -ne 0 ]; then
    kill -TERM "$pid"
    wait "$pid"
  fi
  exit 143; # 128 + 15 -- TERM
}

trap 'kill ${!}; term_handler' TERM

mv /var/smashing-consul.json /opt/consul/conf/smashing-consul.json
mv /var/smashing-goss.yaml /etc/goss/smashing-goss.yaml

/smashing/run.sh &

pid="$!"

tail -f /dev/null & wait ${!}